Develop
kazantipovna/Sprint_6 pull request #1
Opened 2023-12-11 21:37 UTC by kazantipovna

первая версия, спринт 6

2023-12-14 13:15 UTC, kadirovgm requested changes

2023-12-14 13:15 UTC, kadirovgm commented on conftest.py
> +DRIVER_PATH_CHROME = './chromedriver'
Можно лучше: драйвер локально или в проекте держать не очень хороший вариант, так как таким образом можно упустить некоторые обновления драйвера

2023-12-14 13:15 UTC, kadirovgm commented on conftest.py
> +DRIVER_PATH_CHROME = './chromedriver'
Простой код фикстуры для setup и teardown методов:

```
@pytest.fixture()
def driver():
    driver = webdriver.Chrome()
    driver.get(<url main page>)

    yield driver
    driver.quit()

```

2023-12-14 13:15 UTC, kadirovgm commented on pages/base_page.py
> +class BasePageLocators:
Можно лучше: у BasePage не может быть локаторов, потому что это не реальная страница, а абстрактный класс с методами, которые могут быть вызваны на любых POM-страниц

а эти локаторы я бы скорее поместил в MainPage

2023-12-14 13:15 UTC, kadirovgm commented on pages/base_page.py
> +        self.url = 'https://qa-scooter.praktikum-services.ru/'
Нужно исправить: тестовые статичные данные лучше выносить в отдельный файл типа [data.py](http://data.py/) или [urls.py](http://urls.py/)
Это нужно для легкой поддержке проекта и переиспользовании тестовых данных, мы должны стремиться к тому, чтобы разделять код и тестовые данные, тем самым избегая повторений.

2023-12-14 13:15 UTC, kadirovgm commented on pages/base_page.py
> +    def open(self):
нужно исправить: этот метод открывает конкретный url главной страницы, предлагаю в аргументы функции передавать параметр url, чтобы метод мог открывать любую страницу - тогда это будет базовый метод BasePage

сейчас же это скорее метод главной страницы, которая умеет открывать только ее

2023-12-14 13:15 UTC, kadirovgm commented on pages/base_page.py
> +    def get_web_element(self, locator):
отлично! вот это базовый метод

2023-12-14 13:15 UTC, kadirovgm commented on pages/base_page.py
> +    def main_img(self):
нужно исправить: это не метод BasePage, так как возвращает конкретный img

2023-12-14 13:15 UTC, kadirovgm commented on pages/base_page.py
> +    def ya_img(self):
нужно исправить: это не метод BasePage, так как возвращает конкретный img

2023-12-14 13:15 UTC, kadirovgm commented on pages/base_page.py
> +        Повторно кликает в элемент страницы, пока не кликнет успешно, иначе, через attempts_timeout,
прикольно!

2023-12-14 13:15 UTC, kadirovgm commented on pages/base_page.py
> +class BasePage:
Отлично! ты правильно понял консепцию POM и базового класса BasePage

класс BasePage - это такой родительский класс, в котором содержатся общие методы, такие как: клик по определенному элементу, скролл к определенному элементу, ожидание определенного элемента, изменение табов итд.

То есть эти методы не привязаны к определенной странице, и могут быть переиспользованы в любой POM-странице, стоит сюда добавить именно такие методы.

Именно поэтому у BasePage не могут быть свои локаторы, ведь предполагается, что для методов BasePage подходят локаторы POM-страницы

2023-12-14 13:15 UTC, kadirovgm commented on pages/main_page.py
> +    def __init__(self):
можно лучше: для чего этот конструктор? когд можно было просто определить переменные внутри класса

2023-12-14 13:15 UTC, kadirovgm commented on pages/question_page.py
> +    def get_answer_by_number(self, question_number):
хороший метод!

2023-12-14 13:15 UTC, kadirovgm commented on tests/params/data_questions.py
> +text_check = [
Можно лучше: может эти данные поместить в класс? чтобы класс заимпортить, а не весь файл

2023-12-14 13:15 UTC, kadirovgm commented on tests/test_order.py
> +            order_for_who_page.name.send_keys(order_params['name'])
нужно исправить: давай эти мини-методы для заполнения данных объединим в один большой, например, fill_order_info() или что то типа того

мы должны минимизировать количество строк в самих тестах, чтобы в тестах оставались только высокоуровневые шаги

2023-12-14 13:15 UTC, kadirovgm commented on tests/test_order.py
> +            assert expected_form_title in order_for_who_page.form_title.text, \
нужно исправить: мы должны писать атомарные тесты, грубо говоря один тест=одна функциональная проверка (один ассерт), поэтому твои тесты надо нарезать на несколько

2023-12-14 13:15 UTC, kadirovgm commented on tests/test_questions.py
> +        assert expected_answer == question_answer, f'Ошибка: текст не соответствует заданному: {expected_answer}'
это хороший тест!

2023-12-14 19:52 UTC, kazantipovna commented on tests/test_order.py
> +            assert expected_form_title in order_for_who_page.form_title.text, \
++
разбила на отдельно заказ и отдельно переходы по кнопкам

2023-12-14 19:52 UTC, kazantipovna commented on tests/test_questions.py
> +        assert expected_answer == question_answer, f'Ошибка: текст не соответствует заданному: {expected_answer}'
спасибо! :)

2023-12-14 19:54 UTC, kazantipovna commented on tests/test_order.py
> +            order_for_who_page.name.send_keys(order_params['name'])
++
т.к. описывала отдельно странички с формой кому и когда, то вынесла в два метода по заполнению в описание соответствующей страничке

2023-12-14 19:55 UTC, kazantipovna commented on tests/params/data_questions.py
> +text_check = [
++
а и с классом можно не возиться, просто заимпортила список

2023-12-14 19:57 UTC, kazantipovna commented on pages/main_page.py
> +    def __init__(self):
++
и правда) сделано

2023-12-14 19:58 UTC, kazantipovna commented on pages/base_page.py
> +    def ya_img(self):
++
вынесено в main_page

2023-12-14 19:58 UTC, kazantipovna commented on pages/base_page.py
> +    def main_img(self):
++
вынесено в main_page

2023-12-14 19:59 UTC, kazantipovna commented on pages/base_page.py
> +    def open(self):
++
сделано

2023-12-14 19:59 UTC, kazantipovna commented on pages/base_page.py
> +        self.url = 'https://qa-scooter.praktikum-services.ru/'
++
вынесено в отдельный файл с урлами

2023-12-14 19:59 UTC, kazantipovna commented on pages/base_page.py
> +class BasePageLocators:
++
сделано

2023-12-14 20:01 UTC, kazantipovna commented on conftest.py
> +DRIVER_PATH_CHROME = './chromedriver'
наставник говорил делать так ¯\_(ツ)_/¯

2023-12-16 12:55 UTC, kadirovgm approved these changes

2023-12-16 12:55 UTC, kadirovgm commented on conftest.py
> +DRIVER_PATH_CHROME = './chromedriver'
ок

2023-12-16 12:55 UTC, kadirovgm commented on pages/main_page.py
> +    order_top_btn = By.XPATH, "(//button[text()='Заказать'])[1]"
отлично!

2023-12-16 12:55 UTC, kadirovgm commented on pages/order_for_who.py
> +    def fill_form_for_who(self, name, surname, address, station, phone):
супер!

2023-12-17 16:41 UTC, merged